### ISSUE TITLE
0.4.9 Galacticraft bugs

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [bartimaeusnek/bartworks#27]
Crash without Galacticraft installed: https://pastebin.com/1AnhUduj

Crash with Galacticraft when entering newly-created world (but not when re-entering same world): https://pastebin.com/RhdZuwqV

**Comment by bartimaeusnek** [comment]
okay, the first one is fixed now ( can also be manually fixed by disableing the Global Render Patch in the config),
and to the second one:
its most likely that another mod uses the same ID, could you try to change the ID of Ross128b and Ross128ba to other unused values?
see https://www.reddit.com/r/FeedTheBeastCrashes/comments/72y88v/a_solution_to_the_does_not_exist_provider_type/

**Comment by bHXDgiuMa5yLHyC8** [comment]
crash entering world without galacticraft: https://pastebin.com/QKeS4G4j

crash during launch with galacticraft: https://pastebin.com/pH9jciCW

**Comment by bartimaeusnek** [comment]
@bHXDgiuMa5yLHyC8 Should work fine now, both with and without galacticraft.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Seems to be working now.
